apiVersion: apps/v1
kind: Deployment
metadata:
  name: steampipe-deployment
  labels:
    app: steampipe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: steampipe
  template:
    metadata:
      labels:
        app: steampipe
    spec:
      containers:
      - name: steampipe
        image: turbot/steampipe:latest
        command: ["/bin/sh"]
        args:
        - "-c"
        - >- 
          steampipe service start &&
          tail -f  /home/steampipe/.steampipe/logs/*.log  
        ports:
        - containerPort: 80
