apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: temporal-w-spcloudt6t6sk7toegg-tls
  labels:
    workspace-id: w_spcloudct6t6sk7toegg
    identity-id: o_spcloud6un5ogrh1bc0
    region: apse1
    shard: "0001"
    workspace-pluginset: "20220317010004"
    app.kubernetes.io/component: steampipe-workspace-db
    app.kubernetes.io/managed-by: steampipe-api
    app.kubernetes.io/part-of: steampipe-cloud
    app.kubernetes.io/instance: w-spcloudct6t6sk7toegg
    app.kubernetes.io/version: 0.13.3-workspace-spcloud.20220317010004
spec:
  secretName: temporal-w-spcloudt6t6sk7toegg-tls
  duration: 87600h # 10 years
  renewBefore: 360h # 15d
  usages:
    - server auth
    - client auth
  issuerRef:
    name: ca-issuer-temporal
    kind: ClusterIssuer
  dnsNames:
    - w-spcloudt6t6sk7toegg