apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: pgbackrest-w-workspaceo7vfv615dg-server
  labels:
    workspace-id: w_workspaceo7vfv615dg
    identity-id: o_workspacen5ogrh1bc0
    region: apse1
    shard: "0001"
    workspace-pluginset: "20220317010004"
    app.kubernetes.io/component: steampipe-workspace-db
    app.kubernetes.io/managed-by: steampipe-api
    app.kubernetes.io/part-of: steampipe-cloud
    app.kubernetes.io/instance: w-workspaceo7vfv615dg
spec:
  secretName: pgbackrest-w-workspace2o7vfv615dg-tls-server
  duration: 87600h # 10 years
  renewBefore: 360h # 15d
  issuerRef:
    name: ca-issuer-temporal
    kind: ClusterIssuer
  commonName: w-workspacen2o7vfv615dg
  dnsNames:
    - w-workspace2o7vfv615dg